In [ ]:
!pip install numpy

In [9]:
import numpy as np

In [10]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
arr_ones = np.ones(10)
print(arr_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
arr_fives = np.ones(10) * 5
print(arr_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [13]:
arr_10_50 = np.arange(10, 51)
print(arr_10_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [14]:
arr_even = np.arange(10, 51, 2)
print(arr_even)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [15]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
rand_num = np.random.rand()
print(rand_num)


0.4304907950141845


In [18]:
rand_normal = np.random.randn(25)
print(rand_normal)


[-1.18675943  0.57675411  0.04103986  0.40153667  0.01994784  0.32972666
  0.36925514 -0.53408006  1.52717424 -0.41797296 -0.54377502  1.21124574
  1.00090026 -1.1608793   2.10354643  1.34793359 -0.91998213  0.46392812
  0.63153128  1.39192922 -0.56959065 -0.16930078  1.9308754   1.86420362
 -0.41124215]


In [19]:
matrix_10x10 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(matrix_10x10)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [20]:
lin_space = np.linspace(0, 1, 20)
print(lin_space)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [21]:
mat = np.arange(1, 26).reshape(5, 5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [22]:
print(mat[2:, 1:])


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [23]:
print(mat[:3, 1:2])


[[ 2]
 [ 7]
 [12]]


In [24]:
print(mat[4])


[21 22 23 24 25]


In [25]:
print(mat[3:, :])


[[16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
print(np.sum(mat))


325


In [27]:
print(np.std(mat))


7.211102550927978


In [28]:
print(np.sum(mat, axis=0))


[55 60 65 70 75]


In [29]:
print(np.sum(mat, axis=1))


[ 15  40  65  90 115]
